# Generated by Django 5.2.4 on 2025-07-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
