# Generated by Django 5.2.4 on 2025-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_projects", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="project_images/"),
        ),
    ]
