# Generated by Django 5.2.4 on 2025-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0003_alter_certification_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="live_link",
            field=models.FileField(upload_to="certificates/pdfs/"),
        ),
    ]
