# Generated by Django 5.2.4 on 2025-07-30 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0005_alter_certification_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="live_link",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
