# Generated by Django 5.2.4 on 2025-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0006_alter_certification_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="image",
            field=models.ImageField(upload_to="certificates/images/"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="live_link",
            field=models.FileField(upload_to="certificates/pdfs/"),
        ),
    ]
