# Generated by Django 5.2.4 on 2025-07-30 14:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
