# Generated by Django 5.2.4 on 2025-07-30 15:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_resume", "0002_alter_resume_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="live_link",
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name="raw"),
        ),
    ]
